// <auto-generated />
using System;
using Inveon.Services.CategoryAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inveon.Services.CategoryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inveon.Services.CategoryAPI.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kadın"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Erkek"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Çocuk"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Giyim",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ayakkabı",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Aksesuar",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mont",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Eşofman Altı",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Polar",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 10,
                            Name = "Topuklu Ayakkabı",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sneaker",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bot",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "Atkı",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cüzdan",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 15,
                            Name = "Saat",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 16,
                            Name = "Giyim",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ayakkabı",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "Aksesuar",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "Mont",
                            ParentCategoryId = 16
                        },
                        new
                        {
                            Id = 20,
                            Name = "Eşofman Altı",
                            ParentCategoryId = 16
                        },
                        new
                        {
                            Id = 21,
                            Name = "Polar",
                            ParentCategoryId = 16
                        },
                        new
                        {
                            Id = 22,
                            Name = "Sneaker",
                            ParentCategoryId = 17
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bot",
                            ParentCategoryId = 17
                        },
                        new
                        {
                            Id = 24,
                            Name = "Atkı",
                            ParentCategoryId = 18
                        },
                        new
                        {
                            Id = 25,
                            Name = "Cüzdan",
                            ParentCategoryId = 18
                        },
                        new
                        {
                            Id = 26,
                            Name = "Saat",
                            ParentCategoryId = 18
                        },
                        new
                        {
                            Id = 27,
                            Name = "Kız Çocuk",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Erkek Çocuk",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "Mont",
                            ParentCategoryId = 27
                        },
                        new
                        {
                            Id = 30,
                            Name = "Eşofman Altı",
                            ParentCategoryId = 27
                        },
                        new
                        {
                            Id = 31,
                            Name = "Polar",
                            ParentCategoryId = 27
                        },
                        new
                        {
                            Id = 32,
                            Name = "Mont",
                            ParentCategoryId = 28
                        },
                        new
                        {
                            Id = 33,
                            Name = "Eşofman Altı",
                            ParentCategoryId = 28
                        },
                        new
                        {
                            Id = 34,
                            Name = "Polar",
                            ParentCategoryId = 28
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
