// <auto-generated />
using Inveon.Services.BrandAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inveon.Services.BrandAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231122130447_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inveon.Services.BrandAPI.Models.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ontrail"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Defacto"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pull & Bear"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Koton"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zara"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bershka"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Harley Davidson"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Avva"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
