// <auto-generated />
using System;
using Inveon.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inveon.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231120233405_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inveon.Services.ProductAPI.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 11, 21, 2, 34, 5, 300, DateTimeKind.Local).AddTicks(1545),
                            Description = "%100 geri dönüştürülmüş polyester ile üretilmiştir. İçi polarlı, dışı tüylü olduğu için soğuk kış günlerinin kurtarıcısıdır. Dokuma etiket tasarımına sahiptir. Düğmelerde hindistan cevizi kabuğu kullanılmıştır. Unisex, her yaş ve bedene uygun olarak üretilmiştir. Ürünlerimiz ilk aşamadan itibaren çevreye ve ekolojik dengeye duyarlı üretimi benimseyen Oeko-Tex 100 standart sertifikasına sahiptir.",
                            Images = "1_1.webp,1_2.webp,1_3.webp,1_4.webp",
                            IsActive = true,
                            ListPrice = 1495.0,
                            Name = "Cozy Outdoors Sherpa Polar – Kiremit",
                            Quantity = 100,
                            SalePrice = 1200.99
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 11, 21, 2, 34, 5, 300, DateTimeKind.Local).AddTicks(1586),
                            Description = "%100 geri dönüştürülmüş polyester ile üretilmiştir. İçi polarlı, dışı tüylü olduğu için soğuk kış günlerinin kurtarıcısıdır. Dokuma etiket tasarımına sahiptir. Düğmelerde hindistan cevizi kabuğu kullanılmıştır. Unisex, her yaş ve bedene uygun olarak üretilmiştir. Ürünlerimiz ilk aşamadan itibaren çevreye ve ekolojik dengeye duyarlı üretimi benimseyen Oeko-Tex 100 standart sertifikasına sahiptir.",
                            Images = "2_1.webp,2_2.webp,2_3.webp,2_4.webp",
                            IsActive = true,
                            ListPrice = 1695.0,
                            Name = "Cozy Outdoors Sherpa Polar – Krem",
                            Quantity = 100,
                            SalePrice = 1695.0
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 11, 21, 2, 34, 5, 300, DateTimeKind.Local).AddTicks(1595),
                            Description = "Coool jogger ince kumaş eşofman altı, modern tasarımıyla şıklığı rahatlıkla bir araya getirirken, ince kumaşıyla da sizi serin ve rahat tutar. Spor yaparken veya günlük yaşamda rahat ve tarz bir seçenektir. Pamuk 60%,poliester 40%",
                            Images = "3_1.webp,3_2.webp",
                            IsActive = true,
                            ListPrice = 250.0,
                            Name = "Coool Jogger Ince Kumaş Eşofman Altı",
                            Quantity = 50,
                            SalePrice = 209.99000000000001
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 11, 21, 2, 34, 5, 300, DateTimeKind.Local).AddTicks(1603),
                            Description = "Modelin boyu: 177 cm. Farklı renkleri mevcut, fermuarlı, kapüşonlu, dik yaka, yan cepli, şişme mont. 100% polyester KURU TEMİZLEME YAPILAMAZ - 30ºC DE MAKİNADA HASSAS YIKAMA - BEYAZLATICI KULLANILMAZ - 110ºC DERECEDE ÜTÜLEME - MERDANELI TEMIZLEME YAPILAMAZ",
                            Images = "4_1.webp,4_2.webp",
                            IsActive = true,
                            ListPrice = 1390.0,
                            Name = "Kapüşonlu şişme mont",
                            Quantity = 50,
                            SalePrice = 1390.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
